morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java

Sample warning being changed to debug level:
```
WARN org.mongodb.morphia.DatastoreImpl: DBCollection already exists is capped already; doing nothing.
```
This should not be a warning as there is no problem.  The DBCollection
will already exist on every application startup except the first one.
Also fixes grammar of the log message.
Fixes Morphia issue #694.

Downgrade from WARN to DEBUG message about capped collection existing (fixes #694)

---

morphia/src/main/java/org/mongodb/morphia/converters/DefaultConverters.java
morphia/src/main/java/org/mongodb/morphia/geo/GeoJson.java
morphia/src/main/java/org/mongodb/morphia/geo/GeoJsonType.java
morphia/src/main/java/org/mongodb/morphia/geo/Geometry.java
morphia/src/main/java/org/mongodb/morphia/geo/GeometryCollection.java
morphia/src/main/java/org/mongodb/morphia/geo/GeometryConverter.java
morphia/src/main/java/org/mongodb/morphia/geo/GeometryFactory.java
morphia/src/main/java/org/mongodb/morphia/geo/GeometryShapeConverter.java
morphia/src/main/java/org/mongodb/morphia/geo/LineString.java
morphia/src/main/java/org/mongodb/morphia/geo/MultiLineString.java
morphia/src/main/java/org/mongodb/morphia/geo/MultiPoint.java
morphia/src/main/java/org/mongodb/morphia/geo/MultiPolygon.java
morphia/src/main/java/org/mongodb/morphia/geo/Point.java
morphia/src/main/java/org/mongodb/morphia/geo/PointBuilder.java
morphia/src/main/java/org/mongodb/morphia/geo/Polygon.java
morphia/src/main/java/org/mongodb/morphia/query/FieldEndImpl.java
morphia/src/test/java/org/mongodb/morphia/ext/CustomConvertersTest.java
morphia/src/test/java/org/mongodb/morphia/geo/City.java
morphia/src/test/java/org/mongodb/morphia/geo/GeoEntitiesTest.java
morphia/src/test/java/org/mongodb/morphia/geo/GeoJsonIndexTest.java
morphia/src/test/java/org/mongodb/morphia/geo/GeometryCollectionTest.java
morphia/src/test/java/org/mongodb/morphia/geo/GeometryShapeConverterTest.java
morphia/src/test/java/org/mongodb/morphia/query/GeoJsonTest.java

Fixes #643
As per discussions before the holidays, whether or not the Java driver supports geo entities in the future, I would prefer the Morphia API not to leak entities from the Java driver, and therefore it will provide its own geo entities.  In future, these may wrap or convert to entities provided by the underlying driver.

Implemented entities for all Geo types currently supported by MongoDB

---

morphia/src/main/java/org/mongodb/morphia/query/FieldEnd.java
morphia/src/main/java/org/mongodb/morphia/query/FieldEndImpl.java
morphia/src/main/java/org/mongodb/morphia/query/StandardGeoFieldCriteria.java
morphia/src/test/java/org/mongodb/morphia/query/GeoWithinQueriesWithMultiPolygonTest.java
morphia/src/test/java/org/mongodb/morphia/query/GeoWithinQueriesWithPolygonTest.java

Added support for $geoWithin using the new GeoJson entities.  I've called the method "within" as this is consistent with the previous $geoWithin method (the one that that accepts a `Shape`.
Added tests to show how to use the feature with polygons and multi-polygons, and show how it returns documents containing all types of geo entities.
Fixes #644

Support for $geoWithin

---

morphia/src/main/java/org/mongodb/morphia/query/FieldEnd.java
morphia/src/main/java/org/mongodb/morphia/query/FieldEndImpl.java
morphia/src/main/java/org/mongodb/morphia/query/FilterOperator.java
morphia/src/main/java/org/mongodb/morphia/query/StandardGeoFieldCriteria.java
morphia/src/test/java/org/mongodb/morphia/query/GeoIntersectsQueriesWithLineTest.java
morphia/src/test/java/org/mongodb/morphia/query/GeoIntersectsQueriesWithPointTest.java
morphia/src/test/java/org/mongodb/morphia/query/GeoIntersectsQueriesWithPolygonTest.java

Added the API for geoIntersects.  Unlike geoWithin, this method can take any geometry object, so there's only a single method rather than a series of overloaded methods with allowed types.
I've added tests for the basic types (point, line and polygon) to show how the feature works. Technically these "test" the server, but they do show the feature working with the major geometry types.

Issue 645 - Added support for $geoIntersects

---

morphia/src/test/java/org/mongodb/morphia/geo/LegacyCoordsTest.java

I reproduced the steps in issue #275 in a couple of tests, and have proved that the correct queries are being generated. I'm not sure when this functionality was fixed, but it appears to not be a problem in the current version of the code.

Added tests to show that issue #275 is fixed

---

morphia/src/main/java/org/mongodb/morphia/utils/ReflectionUtils.java
morphia/src/test/java/org/mongodb/morphia/utils/ReflectionUtilsTest.java

Changed getParameterizedClass so that if it's passed an interface without generic params that extends an interface with generic params, it will return the super-interface's generic param. Fixes #784.
Limitations: if passed an interface that extends more than one interface with generic params, will return the first only.

Fixed cause of null pointers when passing interfaces into getParameterizedClass

---

docs/reference/content/guides/querying.md

I spent a while working out how to do this, I'd totally missed the DBObject overload of the createQuery method and couldn't find an example of how to mix it with Morphia's built-in querying style. In fact, I'd started writing a "raw" addition to the "filter" method before I realised it must already be there.

Add example of using a raw DBObject style query

---

morphia/src/main/java/org/mongodb/morphia/geo/GeometryShapeConverter.java

This reduces the potential of odd subtle bugs and exposed the fact that there was a call to encode something that didn't need encoding.

Added type safety to the GeometryShapeConverter.

---

morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java

Global entity interceptors are called after entity listeners and lifecycle methods, not before.

Mapper: correct comment describing interceptors field

---

docs/reference/content/guides/querying.md
morphia/src/test/java/org/mongodb/morphia/query/TestTextSearching.java

Fix small typo:
- `guten Nacht` -> `gute Nacht`
http://www.duden.de/rechtschreibung/Nacht

Fix typo (de)

---

morphia/src/main/java/org/mongodb/morphia/AdvancedDatastore.java
morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java
morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationPipelineImpl.java

While `AdvancedDatastore` provides many methods to allow an alternative collection name, the creation of an `AggregationPipeline` is not one of them. This pull request is proposing the simple addition of such a method: `AdvancedDatastore.createAggregation(String, Class<?>);`

Include an AdvancedDatastore-specific method for aggregation

---

morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java
morphia/src/main/java/org/mongodb/morphia/query/FieldEnd.java
morphia/src/main/java/org/mongodb/morphia/query/FieldEndImpl.java
morphia/src/main/java/org/mongodb/morphia/query/QueryImpl.java
morphia/src/test/java/org/mongodb/morphia/TestQuery.java

This is a replacement implementation of $elemMatch.  The old "hasThisElement" and "doesNotHaveThisElement" are being deprecated as they are rather limited in what they support.  This resolves #970.

new implementation of $elemMatch support

---

morphia/src/main/java/org/mongodb/morphia/Datastore.java
morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java
morphia/src/main/java/org/mongodb/morphia/dao/BasicDAO.java
morphia/src/test/java/org/mongodb/morphia/TestUpdateOps.java
morphia/src/test/java/org/mongodb/morphia/TestVersionAnnotation.java

This commit mostly just makes the `update` methods consistent with the changes to the saves and deletes.  The biggest arguable change is the deprecation of the `updateFirst` variants.  Looking at the API it seems there was some attempt at symmetry, over the years, to make `updateFirst` versions of the `update` methods.  This hasn't quite happened, however, and with easy access to `UpdateOptions` now, having `updateFirst` as separate methods makes less sense.  In the spirit of simplifying and streamlining the API, I've elected to deprecate the `updateFirst` methods in favor of the `update` methods.
The tests have been updated to use the correct methods and some new tests introduced to make sure the old methods still get tested.  I did a little bit of clean up to help isolate where we've …

deprecate the `updateFirst` and `update*` methods

---

morphia/src/test/java/org/mongodb/morphia/aggregation/AggregationTest.java

This test always fails for me locally, it shows an actual date of yesterday rather than today.  Adding a specific timezone appears to have fixed it for me.

Added timezone to test so that it no longer fails when run in CET.

---

LICENSE

Using the text of Apache License v. 2.0 provided by Github makes the "nice" badge appear in the section with the most important repository information -- it is a nice practice to provide a license in a uniform manner in every Github repository.
See https://help.github.com/articles/adding-a-license-to-a-repository/.

Corrected the license file to be recognized by Github

---

morphia/src/main/java/org/mongodb/morphia/query/UpdateOpsImpl.java

When a field is not set, i'd be nice to know what field it is - currently we are seeing just `Value cannot be null` and we start the scavenger hunt to find out what the field is. 
Would be good to show field names for ever missing (null) field

add field name to an exception

---

morphia/src/main/java/org/mongodb/morphia/IndexHelper.java
morphia/src/test/java/org/mongodb/morphia/issue1175/EnsureIndexesTest.java

This pull-request should fix the issue #1175 
With this fix indexes from sub-classes will not be propagated on embedded field of a definite class and hence it will not raise an exception during key calculation. This should not break anybodies implementation since creation of indexes in such scenario is blocked anyway (see related issue #1175).
The indexes from sub-classes will be still propagated if class of embedded field is an `interface` or an `abstract class`, which make sense in its own way and it does not break key calculation logic. See corresponding integration test [IndexHelperTest.createIndex()](https://github.com/mongodb/morphia/blob/master/morphia/src/test/java/org/mongodb/morphia/IndexHelperTest.java#L119) where 6 indexes are expected, only 4 indexes are declared in direct …

Fix for ensureIndexes() logic

---

morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java

When calling DAO<T, U>.update(query, operation) and setting a LinkedHashMap in an attribute would result in ordering of that Map being lost due to the usage of HashMap.
I have replaced this usage with a LinkedHashMap and this fixes this issue.

Retain order of Map in update flow

---

morphia/src/main/java/dev/morphia/mapping/MapperOptions.java

This is necessary for some use cases (for example, when working with Spigot/Bukkit JavaPlugins) (see https://spigotmc.org) when the `PluginClassLoader` is used.  In order to prevent `NoClassDefFoundError` for entity classes, the `JavaPlugin`'s ClassLoader needs to be used, and I'm sure this is applicable to other applications as well.
**Example of my use in the previous version (when it was possible to override the DefaultCreator's `getClassLoaderForClass()` method):**
```java
MapperOptions options = morphia.getMapper().getOptions();
morphia.getMapper().setOptions(MapperOptions.builder(options)
.objectFactory(new DefaultCreator(options) {
@Override
protected ClassLoader getClassLoaderForClass() {
return myClassLoader;
}
})
.build());
```
**Example usage with this commit:**
```java …
```

Add classLoader to mapper options builder

---

docs/antora.yml

This shows the new @djencks/antora-javadoc config format and also how to use the sonatype REST api to fetch the latest SNAPSHOT javadoc jar. If you want to keep the configuration in the descriptors rather than the playbook, I think it would be easier to just modify the config yourself than deal with a PR per branch.  If you'd rather have PRs let me know.

new config format, and use sonatype API to fetch SNAPSHOT javadoc jar.

---

core/src/main/java/dev/morphia/mapping/MorphiaDefaultsConvention.java
core/src/test/java/dev/morphia/test/mapping/TestReferenceAnnotationPosition.java

Fixed referencing (and removed embedding) entities if the `@Reference` annotation is not last over a field.
Frankly speaking I'm not entirely sure if this is the best fix, because it will break backward compatibility for souls who saved documents with `@Reference`d entities when the `@Reference` annotation wasn't the very last on a field.
However, it will be a saver for poor souls who (just like me) in their codebase use `@Reference`s mixed with other annotations and Morphia 1 and try to migrate.
I've mentioned that in #1549.
However, if this is a valid fix, I'd ask to backport it.
Thanks!

Fixed referencing (and removed embedding) entities 

---

core/src/test/java/dev/morphia/test/aggregation/experimental/TestDateExpression.java

Added a UTC timezone, which seems to fix the failing tests, but I also had to change the expected value of the day-of-week for August 14 since this is actually a Sunday, and the days are indexed from 1/Monday.
I'll be honest I'm not 100% sure I'm fixing the tests as intended! But these date tests never seem to run correctly from a European timezone and it means the build always fails.

Fixing the ISO Date tests so they run from CET. 

---

docs/modules/ROOT/pages/transactions.adoc

Fixed variable typo.
Based on the context, the variable `account` might be `user`.

Fixed variable typo in transactions.adoc

---

core/src/main/java/dev/morphia/mapping/codec/reader/DocumentReader.java
core/src/test/java/dev/morphia/test/mapping/codec/DocumentReaderTest.java

- `peekBinarySize` should not change state of the reader similar to `peekBinarySubType`
- `readBinaryData`, `peekBinarySubType`,`peekBinarySize` should support same set of types - `UUID`, `Binary`, `BsonBinary`

1599 - make DocumentReader able to handle Binary

---

docs/modules/ROOT/pages/quick-tour.adoc

Updated typo for 'MappingOptions' to 'MapperOptions' to be consistent with Morphia 1.6

Fix MappingOptions -> MapperOptions in Morphia 1.6 Docs

---

core/src/main/java/dev/morphia/annotations/PostLoad.java
core/src/main/java/dev/morphia/annotations/PostPersist.java
core/src/main/java/dev/morphia/annotations/PreLoad.java
core/src/main/java/dev/morphia/annotations/PrePersist.java

No code changes -- just some documentation tweaks. The lifecycle document is a good start, but I still had questions about how each annotation worked, and documenting the annotations seems like the best place to put more info. (It's where I looked first, anyway.)
I tried to only use examples that could be potentially useful -- for example, I didn't add examples of @PostPersist functions that take zero parameters, because I couldn't think of any situation where that would be useful.
This is just a draft -- open to alterations.

Flesh out the documentation for the core lifecycle annotations

---

core/src/main/java/dev/morphia/mapping/codec/BitSetCodec.java
core/src/main/java/dev/morphia/mapping/codec/MorphiaTypesCodecProvider.java
core/src/test/java/dev/morphia/test/mapping/codec/BitSetCodecTest.java

Adds a codec for `java.util.BitSet` as an array of longs. I've also added support for the legacy driver's save format, as that was very helpful to me when upgrading from Morphia 1.X. This gives users an automatic conversion path if they're still on 1.6 or earlier.

BitSet codec

---

.mvn/extensions.xml

This should speed up builds, particularly when changes are limited to just one module. This extension is open source and free to use.
Currently the Morphia full project build (clean verify) is taking 4-9 minutes locally. Using the build cache:
- If you make no changes to the code, the project takes 8 seconds to run (locally). I appreciate this is not super useful since one usually wants to make changes! But without the build cache, this would take the full 4-8 minutes
- If you make a change to Morphia core, the build may take as much time as it usually does, perhaps a little less
- If you make changes to non-core modules or test classes only, the build may take less time, although I have less experience with how the open source build cache works so this would need some investigation
Feel …

Adding the Maven build cache extension. 

---

core/src/main/java/dev/morphia/mapping/codec/MorphiaCodecProvider.java
core/src/test/java/dev/morphia/mapping/codec/MorphiaCodecProviderTest.java
core/src/test/java/dev/morphia/mapping/codec/NoOpMorphiaPropertyCodecProvider.java
core/src/test/resources/META-INF/services/dev.morphia.mapping.codec.MorphiaPropertyCodecProvider

Like the PR title says - prefer to load user-defined custom property codec providers before the library default codec providers. This allows users to override default behavior to provide customizable codec logic for `Map` and `Collection` types, as well as their subclasses.
Added a test here to validate that the NoOp provider I added would load correctly, but I had to add it in a package separate from the existing tests to get access to the protected methods. Not sure if that's something I should avoid here, but generally it's considered good practice to have unit tests live in the same package as the source it's testing. I also had to add a `META-INF/services/MorphiaPropertyCodecProvider` file here to add the No-Op codec provider so that the service loader could access it. I tried …

Prefer to load custom property codec providers before default codec providers.

---

core/src/main/java/dev/morphia/mapping/Mapper.java
core/src/main/java/dev/morphia/query/LegacyQuery.java
core/src/test/java/dev/morphia/test/mapping/codec/TestDocumentWriter.java
core/src/test/java/dev/morphia/test/models/TestDiscriminatorEntity.java
core/src/test/java/dev/morphia/test/query/TestQuery.java
core/src/test/java/dev/morphia/test/query/legacy/TestLegacyQuery.java

This PR tries to ensmarten the inclusion of discriminator values to only the bare essentials to avoid unncessary indexing requirements.
fixes #2833

 Discriminator added to all Queries when Polymorphism is not enabled

---

core/pom.xml
pom.xml

Enables Develocity's Test Distribution feature for `morphia-core` allowing tests to execute in parallel with up to 4 local executors. This is comparable to surefire's `forkCount`, but Test Distribution additionally benefits from optimized test partitioning based on historical test execution times.
From testing various numbers of local executors, 4 seems to be a good sweet spot and is conveniently the number of cores available in the GitHub Actions runners.
* [Build scan with Test Distribution DISABLED](https://ge.solutions-team.gradle.com/s/v7ejw3dyvqvcy/tests/overview) - tests took `4m 5.743s` wall-clock time
* [Build scan with Test Distribution ENABLED](https://ge.solutions-team.gradle.com/s/ckfna3bgrwmsk/tests/overview) - tests took `1m 28.6s` wall-clock time

Enable Test Distribution

---

.gitignore
.mvn/develocity.xml

Enable local build caching with Develocity, so that goals whose inputs have not changed do not need to be re-executed. This should help reduce local build times when making contributions to Morphia.
Note that it is required to run the `clean` lifecycle phase (i.e. `./mvnw clean install` vs just `./mvnw install`) to store outputs to the build cache.
Here is a [Build Scan](https://ge.solutions-team.gradle.com/s/pywbxplsnu4be/performance/execution#avoidance-savings-local-build-cache) where changes were made to a class under `morphia-kotlin` showing the local build cache in action.

Enable Develocity Local Build Cache

---

core/pom.xml
pom.xml

Reverts MorphiaOrg/morphia#3280
Test Distribution requires authentication with Develocity, and was causing builds that validate PRs to fail when run against a fork, since forks do not have access to secrets.
`forkCount` can be used instead to achieve similar behavior (without Test Distribution's optimized test partitioning), and has already been enabled [here](https://github.com/MorphiaOrg/morphia/pull/3068).

Revert "Enable Test Distribution"

---

core/src/main/java/dev/morphia/mapping/Mapper.java

PR to fix an issue, described  in a discussion here: https://github.com/MorphiaOrg/morphia/discussions/2802
and separate issue opened: https://github.com/MorphiaOrg/morphia/issues/3035

Develop morphia thread safety mapper issue

---

core/src/main/java/dev/morphia/mapping/codec/MorphiaMapCodec.java
core/src/test/java/dev/morphia/test/mapping/codec/MorphiaMapCodecTest.java

We've noticed a bug in `MorphiaMapCodec.java` that is it does not return the map it creates but rather always `Map.of()`
This PR fixes that. Test included.
From the user's perspective it's a regression when switching from 2.4.x to 2.5.x
But is especially visible when using `aggregate` and mapping into `Map.class` type.

Fix incorrectly returned value in MorphiaMapCodec.java
