MorphiaOrg/morphia

.gitignore, build.gradle, gradle.properties, morphia/src/main/java/org/mongodb/morphia/mapping/EmbeddedMapper.java, morphia/src/main/java/org/mongodb/morphia/mapping/MappedField.java, morphia/src/test/java/org/mongodb/morphia/TestPerf.java
Added a Perf test and ~4x improved the performance for mapping of multimaps (```Map<String,List<Value>>```)
before:
```
Fetch multimap performance is too slow: 4.03X slower (10375/2575)
```
after: 
```~1.38x slower than raw```
further, added a fix to allow jdk8 to build the code.
=> improve performance of multimaps

morphia/src/main/java/org/mongodb/morphia/query/FieldEnd.java, morphia/src/test/java/org/mongodb/morphia/query/GeoWithinQueriesWithMultiPolygonTest.java
Fixed the tests so they only run on server versions 2.6 and above. Fixes #644
=>  [Geo API 644] Multi-polygon only works with server 2.6 and above

morphia/src/main/java/org/mongodb/morphia/mapping/DefaultCreator.java
Compiler warnings drive me crazy. I spent a week cleaning up all the warnings, I want to keep it that way!
=> Fixed compiler warnings

morphia/src/main/java/org/mongodb/morphia/geo/Point.java, morphia/src/main/java/org/mongodb/morphia/query/FieldEnd.java
@jyemin 
A pretty simple fix but it's essentially what the server did, too.
=> Support more than 2 dimensions when defining a point

.gitignore, docs/landing/layouts/partials/quickStart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/morphia/768)
=> Landing page updates

morphia/src/test/java/org/mongodb/morphia/TestDatastore.java, morphia/src/test/java/org/mongodb/morphia/generics/model/ChildEmbedded.java
I simplified the code of the test, although you can see the original on my issue-755 branch.  This test passes, so I hope this means that the issue has been fixed in more recent code.
=> Created a test based on the example of issue #755

morphia/src/test/java/org/mongodb/morphia/utils/ReflectionUtilsTest.java
I'm making an assumption that this is the real expected behaviour.
=> Added a test to prove the problem of issue #784

morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java
It seems the issue was due to a copy/paste error.
=> Fixed parameter not empty assertion for "reduce"

docs/reference/content/guides/annotations.md
There is no `PostSave` annotation.
=> Correct lifecycle annotation references in annotations guide

morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationPipelineImpl.java, morphia/src/main/java/org/mongodb/morphia/aggregation/GeoNear.java, morphia/src/test/java/org/mongodb/morphia/aggregation/AggregationTest.java
Apparently I created a simple fix to this issue some time ago.  Happy to receive feedback if this isn't exactly the approach to take.
=> Fix #841 - Added support for GeoJSON in GeoNear.

morphia/src/main/java/org/mongodb/morphia/utils/ReflectionUtils.java, morphia/src/test/java/org/mongodb/morphia/MorphiaTest.java, morphia/src/test/java/org/mongodb/morphia/testmappackage/testmapsubpackage/testmapsubsubpackage/SimpleEntityInSubSubPackage.java
=> fixed #924 Why not provide map package recursively?

morphia/src/main/java/org/mongodb/morphia/query/QueryValidator.java, morphia/src/test/java/org/mongodb/morphia/TestArrayUpdates.java
Maybe I'm missing something, but the fix for https://github.com/mongodb/morphia/issues/333 looks quite easy.
=> Don't complain when validating with array ordinals #333

morphia/src/main/java/org/mongodb/morphia/query/UpdateOperations.java, morphia/src/main/java/org/mongodb/morphia/query/UpdateOpsImpl.java, morphia/src/test/java/org/mongodb/morphia/TestUpdateOps.java
- added an overloaded "dec"-method with fieldname and value, of which amount the decrease should be done
=> #1054 $dec supports number argument

morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java, morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java, morphia/src/test/java/org/mongodb/morphia/TestDatastore.java
=> check for null before trying to convert the result

morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java, morphia/src/main/java/org/mongodb/morphia/Morphia.java, morphia/src/test/java/org/mongodb/morphia/TestAdvancedDatastore.java, morphia/src/test/java/org/mongodb/morphia/callbacks/TestPostPersist.java
=> Deprecate Morphia#useBulkWriteOperations

morphia/src/main/java/org/mongodb/morphia/AdvancedDatastore.java, morphia/src/main/java/org/mongodb/morphia/Datastore.java, morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java, morphia/src/main/java/org/mongodb/morphia/DeleteOptions.java, morphia/src/test/java/org/mongodb/morphia/TestDatastore.java
introduces new overloads for deletes with options
deprecates methods that take a WriteConcern directly
=> Complete the support for DeleteOptions

morphia/src/main/java/org/mongodb/morphia/Datastore.java, morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java, morphia/src/test/java/org/mongodb/morphia/TestVersionAnnotation.java
=> disallow calls to updateFirst() on versioned entities

morphia/src/main/java/org/mongodb/morphia/internal/PathTarget.java, morphia/src/test/java/org/mongodb/morphia/TestUpdateOps.java, morphia/src/test/java/org/mongodb/morphia/internal/PathTargetTest.java
this solves https://github.com/mongodb/morphia/issues/1127
=> allow array Indexes as last segment of path + added unit tests

docs/reference/content/guides/indexing.md
options = @IndexOptions must be set in @Index and not in @Field
=> Fix wrong position of IndexOptions in doc

morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationPipeline.java, morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationPipelineImpl.java, morphia/src/test/java/org/mongodb/morphia/aggregation/AggregationTest.java
AggregationPipeline is currently missing support for UnwindOptions.
This PR adds support for UnwindOptions
=>  Add support for UnwindOptions in AggregationPipeline

build.gradle, no-proxy-deps-tests/build.gradle
Cleaning up some mild line noise that is ultimately unnecessary
=> build clean ups

morphia/src/main/java/org/mongodb/morphia/converters/CurrencyConverter.java, morphia/src/main/java/org/mongodb/morphia/converters/DefaultConverters.java, morphia/src/test/java/org/mongodb/morphia/converters/CurrencyConverterTest.java
Stumbled across #617 as well, so I've put this PR together to button up the Currency constructor issue. `gradlew check` came back roses.
Thanks!
=> #617 add java.util.Currency converter

morphia/src/main/java/org/mongodb/morphia/internal/PathTarget.java
Small fix such that resolved is set to true.
=> bugfix: the resolve function would be called multiple times

morphia/src/main/java/xyz/morphia/converters/Converters.java, morphia/src/main/java/xyz/morphia/mapping/MappedClass.java, morphia/src/main/java/xyz/morphia/mapping/MappedField.java, morphia/src/main/java/xyz/morphia/mapping/Mapper.java, morphia/src/test/java/xyz/morphia/TestMapper.java
this resolves #1221 
I added an adhoc unitTest that displays the performance differences. 
It is "@Ignored" as to not slow down the build.
=> performance improvement: memoized some logically static properties

docs/landing/layouts/partials/hero.html
Update "latest documentation" link on the landing page to 1.5
=> Update "latest documentation" link to 1.5

core/src/main/java/dev/morphia/mapping/DiscriminatorLookup.java, core/src/main/java/dev/morphia/mapping/Mapper.java, core/src/test/java/dev/morphia/test/mapping/TestClassLoader.java
=> #1581 respect `MapperOptions` classloader

core/src/main/java/dev/morphia/mapping/codec/pojo/EntityDecoder.java, core/src/main/java/dev/morphia/mapping/codec/pojo/LifecycleDecoder.java, core/src/test/java/dev/morphia/test/mapping/codec/pojo/DiscriminantLifecycleTest.java
respect discriminator when deserializing entity with lifecycle
=> #1586 deserialization of polymorphic entities with lifecycle

core/src/main/java/dev/morphia/aggregation/experimental/codecs/stages/LookupCodec.java, core/src/main/java/dev/morphia/aggregation/experimental/stages/Lookup.java, core/src/test/java/dev/morphia/test/aggregation/experimental/TestAggregation.java
=> core: add lookup with pipeline

core/src/main/java/dev/morphia/mapping/codec/references/ReferenceCodec.java
This PR adds caching of generated proxy classes to `ReferenceCodec` in order avoid superfluous byte code generation and class loading which is quite expensive when done for each and every instance of a reference type.
Having caching in place improved overall performance in our production system significantly and should help other users fighting with poor performance when using `@Reference(idOnly=true)` as well.
Changes to `ReferenceCodec`:
- Generate proxy class for given reference type only once instead for each instance of that reference type
- Proxy classes are cached by Byte Buddy's type cache and store the respective invocation handler as instance field value
=> #1648: Cache generated proxy classes

.github/workflows/build.yml, core/src/main/java/dev/morphia/mapping/Mapper.java, core/src/main/java/dev/morphia/mapping/codec/pojo/EntityModel.java, core/src/main/java/dev/morphia/mapping/codec/pojo/PropertyModel.java, core/src/test/java/dev/morphia/test/mapping/TestMapper.java
=> rework Mapper cloning to address some performance issues
